FROM 3mpr/python:3-glibc
MAINTAINER oragelac <calegaroantoine@gmail.com>

WORKDIR /tmp

ENV DEPS="mysql mysql-dev" \
    DEV_DEPS="python3 python3-dev glibc gcc musl-dev"

RUN set -ex \
 && apk add --update --no-cache ${DEPS}  \
 && apk add --update --no-cache --virtual .deps ${DEV_DEPS} \
 && pip install --upgrade django mysqlclient \
 && mkdir -p /usr/src/app && addgroup django \
 && adduser -D -g "" -G django -h /usr/src/app -s /sbin/nologin django \
 && chown -R django:django /usr/src/app \
 && apk del .deps

COPY ["entrypoint.sh", "/"]
VOLUME /usr/src/app

ENTRYPOINT ["dumb-init", "--"]
CMD ["/entrypoint.sh"]
