---

version: '2'

services:

    baseimage:
        build: ./baseimage
        image: 3mpr/baseimage:0.1


    erldns:
        build: ./erldns
        image: 3mpr/erldns:latest
        container_name: erldns
        hostname: erldns
        restart: on-failure
        ports:
            - "53:8053/udp"
        volumes:
            - ${HOME}/Documents/Docker/erldns:/tmp/erl-dns/conf
        stdin_open: true
        tty: true

    easyrsa:
        build: ./easyrsa
        image: 3mpr/easyrsa:latest
        container_name: easyrsa
        hostname: easyrsa
        restart: on-failure
        volumes:
            - easyrsa-pki-data:/tmp/EasyRSA-3.0.1/pki
        stdin_open: true
        tty: true

    php:
        build: ./php
        image: 3mpr/php:latest


    laravel-dev:
        build: ./laravel-dev
        image: 3mpr/laravel-dev:5.4
        container_name: laravel-dev
        restart: unless-stopped
        ports:
            - 8000:8000
            - 8080:8080
        volumes:
            - ${HOME}/Documents/Docker/laravel-dev:/home/www-data/app
        environment:
            MIX_ENV: 'hot'


    mysql:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        ports:
            - 3600:3600

volumes:
    easyrsa-pki-data:
