---

version: '2'

services:

    gestalt:
        build:
            context: ./gestalt
            dockerfile: Dockerfile
        image: 3mpr/nginx-gestalt:latest

    baseimage:
        build:
            context: ./baseimage
            dockerfile: Dockerfile-Alpine
        image: 3mpr/baseimage:latest

    baseimage-glibc:
        build:
            context: ./baseimage
            dockerfile: Dockerfile-Alpine-glibc
        image: 3mpr/baseimage:glibc-latest

    baseimage-debian:
        build:
            context: ./baseimage
            dockerfile: Dockerfile-Debian
        image: 3mpr/baseimage:debian-latest

    java:
        build: ./java
        image: 3mpr/java:latest

    python:
        build:
            context: ./python
            dockerfile: 3-Dockerfile
        image: 3mpr/python:3

    erldns:
        build: ./erldns
        image: 3mpr/erldns:latest
        container_name: erldns
        hostname: erldns
        restart: on-failure
        ports:
            - "53:8053/udp"
        volumes:
            - ${HOME}/Documents/Docker/erldns:/tmp/erl-dns/conf
        stdin_open: true
        tty: true

    oscar:
      build: ./oscar
      image: 3mpr/oscar:latest

    php:
        build: ./php
        image: 3mpr/php:latest

    nginx-php:
        build: ./nginx-boilerplate
        image: 3mpr/nginx:php

    laravel-dev:
        build: ./laravel-dev
        image: 3mpr/laravel-dev:5.4
        container_name: laravel-dev
        restart: unless-stopped
        ports:
            - 8000:8000
            - 8080:8080
        volumes:
            - ${HOME}/Documents/Docker/laravel-dev:/home/www-data/app
        environment:
            MIX_ENV: 'hot'

    mysql:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        ports:
            - 3600:3600

    tinc:
        build: ./tinc
        image: 3mpr/tinc:latest

    aoedia:
        build: ./aoedia
        image: 3mpr/aoedia:latest

    ilanga:
        build: ./ilanga
        image: 3mpr/ilanga:0.0.5

    teamspeak:
        build: ./docker-teamspeak
        image: 3mpr/teamspeak:3.3.0
