FROM findot/baseimage:latest
MAINTAINER Florian Indot <florian.indot@gmail.com>

ENV GLIBC_MAJOR_VERSION="2" \
    GLIBC_MINOR_VERSION="30" \
    GLIBC_RELEASE="r0"
ENV GLIBC_PACKAGE="glibc-${GLIBC_MAJOR_VERSION}.${GLIBC_MINOR_VERSION}-${GLIBC_RELEASE}"

ENV DEPS \
    ca-certificates \
    openssl

RUN apk add --update --no-cache --virtual deps $DEPS

RUN set -x \
 && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
 && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_MAJOR_VERSION}.${GLIBC_MINOR_VERSION}-${GLIBC_RELEASE}/${GLIBC_PACKAGE}.apk \
 && apk add ${GLIBC_PACKAGE}.apk

RUN apk del deps

ENTRYPOINT ["/usr/local/bin/dumb-init", "--"]
